// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_alert.sql

package db

import (
	"context"
)

const getAccountAlert = `-- name: GetAccountAlert :one
SELECT account_id, low_balance_threshold, high_balance_threshold, created_at, updated_at FROM account_alerts
WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetAccountAlert(ctx context.Context, accountID int64) (AccountAlert, error) {
	row := q.db.QueryRow(ctx, getAccountAlert, accountID)
	var i AccountAlert
	err := row.Scan(
		&i.AccountID,
		&i.LowBalanceThreshold,
		&i.HighBalanceThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccountAlert = `-- name: UpsertAccountAlert :one
INSERT INTO account_alerts (
  account_id,
  low_balance_threshold,
  high_balance_threshold
) VALUES (
  $1, $2, $3
)
ON CONFLICT (account_id)
DO UPDATE SET
  low_balance_threshold = EXCLUDED.low_balance_threshold,
  high_balance_threshold = EXCLUDED.high_balance_threshold,
  updated_at = now()
RETURNING account_id, low_balance_threshold, high_balance_threshold, created_at, updated_at
`

type UpsertAccountAlertParams struct {
	AccountID            int64 `json:"account_id"`
	LowBalanceThreshold  int64 `json:"low_balance_threshold"`
	HighBalanceThreshold int64 `json:"high_balance_threshold"`
}

func (q *Queries) UpsertAccountAlert(ctx context.Context, arg UpsertAccountAlertParams) (AccountAlert, error) {
	row := q.db.QueryRow(ctx, upsertAccountAlert, arg.AccountID, arg.LowBalanceThreshold, arg.HighBalanceThreshold)
	var i AccountAlert
	err := row.Scan(
		&i.AccountID,
		&i.LowBalanceThreshold,
		&i.HighBalanceThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
