// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.4
// source: rpc_account_alerts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountAlertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetAccountAlertRequest) Reset() {
	*x = GetAccountAlertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_alerts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountAlertRequest) ProtoMessage() {}

func (x *GetAccountAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_alerts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAccountAlertRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountAlertRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetAccountAlertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alert *AccountAlert `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
}

func (x *GetAccountAlertResponse) Reset() {
	*x = GetAccountAlertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_alerts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountAlertResponse) ProtoMessage() {}

func (x *GetAccountAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_alerts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountAlertResponse.ProtoReflect.Descriptor instead.
func (*GetAccountAlertResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountAlertResponse) GetAlert() *AccountAlert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type UpsertAccountAlertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId            int64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LowBalanceThreshold  int64 `protobuf:"varint,2,opt,name=low_balance_threshold,json=lowBalanceThreshold,proto3" json:"low_balance_threshold,omitempty"`
	HighBalanceThreshold int64 `protobuf:"varint,3,opt,name=high_balance_threshold,json=highBalanceThreshold,proto3" json:"high_balance_threshold,omitempty"`
}

func (x *UpsertAccountAlertRequest) Reset() {
	*x = UpsertAccountAlertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_alerts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAccountAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountAlertRequest) ProtoMessage() {}

func (x *UpsertAccountAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_alerts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountAlertRequest.ProtoReflect.Descriptor instead.
func (*UpsertAccountAlertRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_alerts_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertAccountAlertRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpsertAccountAlertRequest) GetLowBalanceThreshold() int64 {
	if x != nil {
		return x.LowBalanceThreshold
	}
	return 0
}

func (x *UpsertAccountAlertRequest) GetHighBalanceThreshold() int64 {
	if x != nil {
		return x.HighBalanceThreshold
	}
	return 0
}

type UpsertAccountAlertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alert *AccountAlert `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
}

func (x *UpsertAccountAlertResponse) Reset() {
	*x = UpsertAccountAlertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_alerts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAccountAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountAlertResponse) ProtoMessage() {}

func (x *UpsertAccountAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_alerts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountAlertResponse.ProtoReflect.Descriptor instead.
func (*UpsertAccountAlertResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_alerts_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertAccountAlertResponse) GetAlert() *AccountAlert {
	if x != nil {
		return x.Alert
	}
	return nil
}

var File_rpc_account_alerts_proto protoreflect.FileDescriptor

var file_rpc_account_alerts_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x52, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x19, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x6c, 0x6f, 0x77, 0x5f, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x6c, 0x6f, 0x77, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x68, 0x69,
	0x67, 0x68, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x68, 0x69, 0x67, 0x68,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x22, 0x44, 0x0a, 0x1a, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52,
	0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x63, 0x68, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2f,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_account_alerts_proto_rawDescOnce sync.Once
	file_rpc_account_alerts_proto_rawDescData = file_rpc_account_alerts_proto_rawDesc
)

func file_rpc_account_alerts_proto_rawDescGZIP() []byte {
	file_rpc_account_alerts_proto_rawDescOnce.Do(func() {
		file_rpc_account_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_account_alerts_proto_rawDescData)
	})
	return file_rpc_account_alerts_proto_rawDescData
}

var file_rpc_account_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_account_alerts_proto_goTypes = []interface{}{
	(*GetAccountAlertRequest)(nil),     // 0: pb.GetAccountAlertRequest
	(*GetAccountAlertResponse)(nil),    // 1: pb.GetAccountAlertResponse
	(*UpsertAccountAlertRequest)(nil),  // 2: pb.UpsertAccountAlertRequest
	(*UpsertAccountAlertResponse)(nil), // 3: pb.UpsertAccountAlertResponse
	(*AccountAlert)(nil),               // 4: pb.AccountAlert
}
var file_rpc_account_alerts_proto_depIdxs = []int32{
	4, // 0: pb.GetAccountAlertResponse.alert:type_name -> pb.AccountAlert
	4, // 1: pb.UpsertAccountAlertResponse.alert:type_name -> pb.AccountAlert
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_account_alerts_proto_init() }
func file_rpc_account_alerts_proto_init() {
	if File_rpc_account_alerts_proto != nil {
		return
	}
	file_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_account_alerts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountAlertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_account_alerts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountAlertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_account_alerts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAccountAlertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_account_alerts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAccountAlertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_account_alerts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_account_alerts_proto_goTypes,
		DependencyIndexes: file_rpc_account_alerts_proto_depIdxs,
		MessageInfos:      file_rpc_account_alerts_proto_msgTypes,
	}.Build()
	File_rpc_account_alerts_proto = out.File
	file_rpc_account_alerts_proto_rawDesc = nil
	file_rpc_account_alerts_proto_goTypes = nil
	file_rpc_account_alerts_proto_depIdxs = nil
}
