// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.4
// source: rpc_account_limits.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetAccountLimitRequest) Reset() {
	*x = GetAccountLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_limits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountLimitRequest) ProtoMessage() {}

func (x *GetAccountLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_limits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountLimitRequest.ProtoReflect.Descriptor instead.
func (*GetAccountLimitRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_limits_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountLimitRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetAccountLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit *AccountLimit `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetAccountLimitResponse) Reset() {
	*x = GetAccountLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_limits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountLimitResponse) ProtoMessage() {}

func (x *GetAccountLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_limits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountLimitResponse.ProtoReflect.Descriptor instead.
func (*GetAccountLimitResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_limits_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountLimitResponse) GetLimit() *AccountLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type UpsertAccountLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId          int64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DailyTransferLimit int64 `protobuf:"varint,2,opt,name=daily_transfer_limit,json=dailyTransferLimit,proto3" json:"daily_transfer_limit,omitempty"`
}

func (x *UpsertAccountLimitRequest) Reset() {
	*x = UpsertAccountLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_limits_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAccountLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountLimitRequest) ProtoMessage() {}

func (x *UpsertAccountLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_limits_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountLimitRequest.ProtoReflect.Descriptor instead.
func (*UpsertAccountLimitRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_limits_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertAccountLimitRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpsertAccountLimitRequest) GetDailyTransferLimit() int64 {
	if x != nil {
		return x.DailyTransferLimit
	}
	return 0
}

type UpsertAccountLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit *AccountLimit `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *UpsertAccountLimitResponse) Reset() {
	*x = UpsertAccountLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_account_limits_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAccountLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountLimitResponse) ProtoMessage() {}

func (x *UpsertAccountLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_limits_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountLimitResponse.ProtoReflect.Descriptor instead.
func (*UpsertAccountLimitResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_limits_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertAccountLimitResponse) GetLimit() *AccountLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

var File_rpc_account_limits_proto protoreflect.FileDescriptor

var file_rpc_account_limits_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x6c, 0x0a, 0x19, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x12, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x44, 0x0a, 0x1a, 0x55, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x63, 0x68,
	0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e,
	0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_account_limits_proto_rawDescOnce sync.Once
	file_rpc_account_limits_proto_rawDescData = file_rpc_account_limits_proto_rawDesc
)

func file_rpc_account_limits_proto_rawDescGZIP() []byte {
	file_rpc_account_limits_proto_rawDescOnce.Do(func() {
		file_rpc_account_limits_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_account_limits_proto_rawDescData)
	})
	return file_rpc_account_limits_proto_rawDescData
}

var file_rpc_account_limits_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_account_limits_proto_goTypes = []interface{}{
	(*GetAccountLimitRequest)(nil),     // 0: pb.GetAccountLimitRequest
	(*GetAccountLimitResponse)(nil),    // 1: pb.GetAccountLimitResponse
	(*UpsertAccountLimitRequest)(nil),  // 2: pb.UpsertAccountLimitRequest
	(*UpsertAccountLimitResponse)(nil), // 3: pb.UpsertAccountLimitResponse
	(*AccountLimit)(nil),               // 4: pb.AccountLimit
}
var file_rpc_account_limits_proto_depIdxs = []int32{
	4, // 0: pb.GetAccountLimitResponse.limit:type_name -> pb.AccountLimit
	4, // 1: pb.UpsertAccountLimitResponse.limit:type_name -> pb.AccountLimit
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_account_limits_proto_init() }
func file_rpc_account_limits_proto_init() {
	if File_rpc_account_limits_proto != nil {
		return
	}
	file_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_account_limits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_account_limits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_account_limits_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAccountLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_account_limits_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAccountLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_account_limits_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_account_limits_proto_goTypes,
		DependencyIndexes: file_rpc_account_limits_proto_depIdxs,
		MessageInfos:      file_rpc_account_limits_proto_msgTypes,
	}.Build()
	File_rpc_account_limits_proto = out.File
	file_rpc_account_limits_proto_rawDesc = nil
	file_rpc_account_limits_proto_goTypes = nil
	file_rpc_account_limits_proto_depIdxs = nil
}
